// Generated by CoffeeScript 1.9.3

/*
 * 删除文件或者是某个目录
 * @author jackie Lin <dashi_lin@163.com>
 */
'use strict';
var FS, _, path, through2;

through2 = require('through2');

FS = require('q-io/fs');

path = require('path');

_ = require('lodash');

module.exports = function(filePath) {
  filePath = _.isFunction(filePath) ? filePath() : filePath;
  return through2.obj(function(file, enc, callback) {
    return FS.stat(filePath).then(function(stat) {
      if (stat.isDirectory()) {
        return FS.list(filePath);
      }
      if (!stat.isDirectory()) {
        return [];
      }
    }).then(function(list) {
      var task;
      task = [];
      list.forEach(function(v) {
        return task.push(FS.remove(path.join(filePath, v)));
      });
      return task;
    }).spread(function() {
      return callback(null, file);
    }).fail(function(err) {
      return FS.makeTree(filePath).then(function() {
        return callback(null, file);
      });
    });
  });
};
