// Generated by CoffeeScript 1.9.3

/*
 * 对文件进行重命名
 * @author jackie Lin <dashi_lin@163.com>
 */
'use strict';
var _, path, through2;

through2 = require('through2');

path = require('path');

_ = require('lodash');

module.exports = function(fn) {
  return through2.obj(function(file, enc, callback) {
    file = _.isFunction(fn) ? fn(file) : fn;
    return callback(null, file);
  });
};
