// Generated by CoffeeScript 1.10.0

/*
 * 处理 require js 文件的相关细节
 * @author jackie Lin <dashi_lin@163.com>
 */
'use strict';
var FS, config, generator, getConfig, getDevConfig, getRelativePath, init, path, through2, writeConfig, writeConfigFile;

through2 = require('through2');

path = require('path');

config = {};

FS = require('q-io/fs');


/*
 * 生成基本的配置信息
 * @return {String} config
 */

getDevConfig = function(msg) {
  return JSON.stringify(msg, null, 4);
};

getConfig = function(msg) {
  return JSON.stringify(msg);
};


/*
 * 根据配置返回 config.js 文件
 * @return {String}  require js string
 */

generator = function(configMsg) {
  return "requirejs.config(" + configMsg + ");";
};


/*
 * 初始化 config 信息
 */

init = function(config) {
  config.requireObj = {};
  config.requireConfig.paths = config.requireConfig.paths || {};
  config.requireObj.baseUrl = path.join(config.sourePath, config.requireConfig.baseUrl);
  return config;
};


/*
 * 设置配置文件信息
 */

exports.setConfig = function(projectConfig) {
  config = projectConfig;
  return init(config);
};


/*
 * 写入配置文件
 * @param {Function} method getConfig || getDevConfig
 */

writeConfigFile = function(configFilePath, method) {
  var configFile, sourePath;
  if (method == null) {
    method = function() {};
  }
  sourePath = config.sourePath;
  configFile = FS.join(sourePath, configFilePath);
  return FS.write(configFile, generator(method(config.requireConfig)));
};


/*
 * 获取 requireJs paths 相对路径
 */

getRelativePath = function() {
  var cwd, requireOption;
  requireOption = config.requireOption || {};
  cwd = requireOption.cwd || config.requireObj.baseUrl;
  return path.join(config.sourePath, cwd);
};


/*
 * 生成配置信息
 */

writeConfig = function(filePath, fileKey) {
  var baseName, key;
  if (fileKey == null) {
    fileKey = function() {};
  }
  baseName = path.basename(filePath, '.js');
  key = fileKey(baseName);
  return config.requireConfig.paths[key] = path.join(path.relative(getRelativePath(), filePath), '../', baseName);
};


/*
 * 重新生成 config dev 信息
 */

exports.rebuildDev = function(fileKey) {
  return through2.obj(function(file, enc, callback) {
    writeConfig(file.path, fileKey);
    writeConfigFile(config.configFile.dev, getDevConfig);
    return callback(null, file);
  });
};


/*
 * 重新生成 config 文件信息
 */

exports.rebuild = function(fileKey) {
  return through2.obj(function(file, enc, callback) {
    writeConfig(file.path, fileKey);
    writeConfigFile(config.configFile.production, getConfig);
    return callback(null, file);
  });
};

exports.getDevConfig = getDevConfig;

exports.getConfig = getConfig;

exports.generator = generator;

exports.writeConfigFile = writeConfigFile;
